import { createFileRoute } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import { createServerFn } from "@tanstack/react-start";
import { requireSupabaseAuth } from "@/integrations/supabase/auth-middleware";
import { PageHeader, Card } from "@/components/PageShell";

export const adminListSignals = createServerFn({ method: "GET" })
  .middleware([requireSupabaseAuth])
  .handler(async ({ context }) => {
    const { supabaseAdmin } = await import("@/integrations/supabase/client.server");
    const { data: roles } = await supabaseAdmin.from("user_roles").select("role").eq("user_id", context.userId);
    if (!roles?.some((r) => r.role === "admin")) throw new Error("Admin required");
    const { data } = await supabaseAdmin
      .from("signals")
      .select("*")
      .order("created_at", { ascending: false })
      .limit(200);
    return data ?? [];
  });

export const Route = createFileRoute("/_authenticated/admin/ai/signals")({
  component: SignalLog,
  head: () => ({ meta: [{ title: "Signal Audit · Admin" }] }),
});

function SignalLog() {
  const fn = useServerFn(adminListSignals);
  const q = useQuery({ queryKey: ["admin-signals"], queryFn: () => fn() });
  const rows = q.data ?? [];

  return (
    <>
      <PageHeader title="Signal Audit Log" subtitle="Every signal ever generated by Genius AI." />
      <div className="p-4 lg:p-8">
        <Card className="overflow-x-auto p-0">
          {rows.length === 0 ? (
            <div className="p-8 text-center text-xs text-muted-foreground">
              {q.isLoading ? "Loading…" : "No signals generated yet."}
            </div>
          ) : (
            <table className="w-full min-w-[700px] text-sm">
              <thead className="text-xs uppercase text-muted-foreground"><tr>
                <th className="p-3 text-left">Pair</th><th className="p-3">Decision</th><th className="p-3">Confidence</th><th className="p-3">When</th>
              </tr></thead>
              <tbody>
                {rows.map((s) => (
                  <tr key={s.id} className="border-t border-border/40">
                    <td className="p-3 font-mono text-xs">{s.pair ?? "—"}</td>
                    <td className="p-3 text-center font-semibold">{s.decision ?? "—"}</td>
                    <td className="p-3 text-center text-xs">{s.confidence ?? "—"}</td>
                    <td className="p-3 text-center text-xs text-muted-foreground">{new Date(s.created_at).toLocaleString()}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          )}
        </Card>
      </div>
    </>
  );
}
