/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedMessagesRouteImport } from './routes/_authenticated/messages'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated/billing'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedDashboardSupportRouteImport } from './routes/_authenticated/dashboard.support'
import { Route as AuthenticatedDashboardSignalsRouteImport } from './routes/_authenticated/dashboard.signals'
import { Route as AuthenticatedDashboardSettingsRouteImport } from './routes/_authenticated/dashboard.settings'
import { Route as AuthenticatedDashboardSandboxRouteImport } from './routes/_authenticated/dashboard.sandbox'
import { Route as AuthenticatedDashboardMetricsRouteImport } from './routes/_authenticated/dashboard.metrics'
import { Route as AuthenticatedDashboardMacroRouteImport } from './routes/_authenticated/dashboard.macro'
import { Route as AuthenticatedDashboardBotRouteImport } from './routes/_authenticated/dashboard.bot'
import { Route as AuthenticatedDashboardAutomationRouteImport } from './routes/_authenticated/dashboard.automation'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminSecretsRouteImport } from './routes/_authenticated/admin.secrets'
import { Route as AuthenticatedAdminMessagesRouteImport } from './routes/_authenticated/admin.messages'
import { Route as AuthenticatedAdminDashboardRouteImport } from './routes/_authenticated/admin.dashboard'
import { Route as ApiPublicPaystackWebhookRouteImport } from './routes/api/public/paystack.webhook'
import { Route as ApiPublicNowpaymentsWebhookRouteImport } from './routes/api/public/nowpayments.webhook'
import { Route as AuthenticatedAdminUsersRiskRouteImport } from './routes/_authenticated/admin.users.risk'
import { Route as AuthenticatedAdminUsersComplianceRouteImport } from './routes/_authenticated/admin.users.compliance'
import { Route as AuthenticatedAdminUsersAllRouteImport } from './routes/_authenticated/admin.users.all'
import { Route as AuthenticatedAdminSupportTicketsRouteImport } from './routes/_authenticated/admin.support.tickets'
import { Route as AuthenticatedAdminSupportBroadcastRouteImport } from './routes/_authenticated/admin.support.broadcast'
import { Route as AuthenticatedAdminSettingsTeamRouteImport } from './routes/_authenticated/admin.settings.team'
import { Route as AuthenticatedAdminSettingsAuditRouteImport } from './routes/_authenticated/admin.settings.audit'
import { Route as AuthenticatedAdminBillingTransactionsRouteImport } from './routes/_authenticated/admin.billing.transactions'
import { Route as AuthenticatedAdminBillingSubscriptionsRouteImport } from './routes/_authenticated/admin.billing.subscriptions'
import { Route as AuthenticatedAdminBillingAnalyticsRouteImport } from './routes/_authenticated/admin.billing.analytics'
import { Route as AuthenticatedAdminBillingAffiliatesRouteImport } from './routes/_authenticated/admin.billing.affiliates'
import { Route as AuthenticatedAdminAutomationBotsRouteImport } from './routes/_authenticated/admin.automation.bots'
import { Route as AuthenticatedAdminAiSignalsRouteImport } from './routes/_authenticated/admin.ai.signals'
import { Route as AuthenticatedAdminAiPlaygroundRouteImport } from './routes/_authenticated/admin.ai.playground'
import { Route as AuthenticatedAdminAiFeedsRouteImport } from './routes/_authenticated/admin.ai.feeds'
import { Route as AuthenticatedAdminAiCouncilRouteImport } from './routes/_authenticated/admin.ai.council'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMessagesRoute = AuthenticatedMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardSupportRoute =
  AuthenticatedDashboardSupportRouteImport.update({
    id: '/support',
    path: '/support',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardSignalsRoute =
  AuthenticatedDashboardSignalsRouteImport.update({
    id: '/signals',
    path: '/signals',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardSettingsRoute =
  AuthenticatedDashboardSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardSandboxRoute =
  AuthenticatedDashboardSandboxRouteImport.update({
    id: '/sandbox',
    path: '/sandbox',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardMetricsRoute =
  AuthenticatedDashboardMetricsRouteImport.update({
    id: '/metrics',
    path: '/metrics',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardMacroRoute =
  AuthenticatedDashboardMacroRouteImport.update({
    id: '/macro',
    path: '/macro',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardBotRoute =
  AuthenticatedDashboardBotRouteImport.update({
    id: '/bot',
    path: '/bot',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAutomationRoute =
  AuthenticatedDashboardAutomationRouteImport.update({
    id: '/automation',
    path: '/automation',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/admin/settings',
    path: '/admin/settings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminSecretsRoute =
  AuthenticatedAdminSecretsRouteImport.update({
    id: '/admin/secrets',
    path: '/admin/secrets',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminMessagesRoute =
  AuthenticatedAdminMessagesRouteImport.update({
    id: '/admin/messages',
    path: '/admin/messages',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminDashboardRoute =
  AuthenticatedAdminDashboardRouteImport.update({
    id: '/admin/dashboard',
    path: '/admin/dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiPublicPaystackWebhookRoute =
  ApiPublicPaystackWebhookRouteImport.update({
    id: '/api/public/paystack/webhook',
    path: '/api/public/paystack/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicNowpaymentsWebhookRoute =
  ApiPublicNowpaymentsWebhookRouteImport.update({
    id: '/api/public/nowpayments/webhook',
    path: '/api/public/nowpayments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminUsersRiskRoute =
  AuthenticatedAdminUsersRiskRouteImport.update({
    id: '/admin/users/risk',
    path: '/admin/users/risk',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminUsersComplianceRoute =
  AuthenticatedAdminUsersComplianceRouteImport.update({
    id: '/admin/users/compliance',
    path: '/admin/users/compliance',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminUsersAllRoute =
  AuthenticatedAdminUsersAllRouteImport.update({
    id: '/admin/users/all',
    path: '/admin/users/all',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminSupportTicketsRoute =
  AuthenticatedAdminSupportTicketsRouteImport.update({
    id: '/admin/support/tickets',
    path: '/admin/support/tickets',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminSupportBroadcastRoute =
  AuthenticatedAdminSupportBroadcastRouteImport.update({
    id: '/admin/support/broadcast',
    path: '/admin/support/broadcast',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminSettingsTeamRoute =
  AuthenticatedAdminSettingsTeamRouteImport.update({
    id: '/team',
    path: '/team',
    getParentRoute: () => AuthenticatedAdminSettingsRoute,
  } as any)
const AuthenticatedAdminSettingsAuditRoute =
  AuthenticatedAdminSettingsAuditRouteImport.update({
    id: '/audit',
    path: '/audit',
    getParentRoute: () => AuthenticatedAdminSettingsRoute,
  } as any)
const AuthenticatedAdminBillingTransactionsRoute =
  AuthenticatedAdminBillingTransactionsRouteImport.update({
    id: '/admin/billing/transactions',
    path: '/admin/billing/transactions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminBillingSubscriptionsRoute =
  AuthenticatedAdminBillingSubscriptionsRouteImport.update({
    id: '/admin/billing/subscriptions',
    path: '/admin/billing/subscriptions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminBillingAnalyticsRoute =
  AuthenticatedAdminBillingAnalyticsRouteImport.update({
    id: '/admin/billing/analytics',
    path: '/admin/billing/analytics',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminBillingAffiliatesRoute =
  AuthenticatedAdminBillingAffiliatesRouteImport.update({
    id: '/admin/billing/affiliates',
    path: '/admin/billing/affiliates',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminAutomationBotsRoute =
  AuthenticatedAdminAutomationBotsRouteImport.update({
    id: '/admin/automation/bots',
    path: '/admin/automation/bots',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminAiSignalsRoute =
  AuthenticatedAdminAiSignalsRouteImport.update({
    id: '/admin/ai/signals',
    path: '/admin/ai/signals',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminAiPlaygroundRoute =
  AuthenticatedAdminAiPlaygroundRouteImport.update({
    id: '/admin/ai/playground',
    path: '/admin/ai/playground',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminAiFeedsRoute =
  AuthenticatedAdminAiFeedsRouteImport.update({
    id: '/admin/ai/feeds',
    path: '/admin/ai/feeds',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminAiCouncilRoute =
  AuthenticatedAdminAiCouncilRouteImport.update({
    id: '/admin/ai/council',
    path: '/admin/ai/council',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/messages': typeof AuthenticatedMessagesRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/messages': typeof AuthenticatedAdminMessagesRoute
  '/admin/secrets': typeof AuthenticatedAdminSecretsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRouteWithChildren
  '/dashboard/automation': typeof AuthenticatedDashboardAutomationRoute
  '/dashboard/bot': typeof AuthenticatedDashboardBotRoute
  '/dashboard/macro': typeof AuthenticatedDashboardMacroRoute
  '/dashboard/metrics': typeof AuthenticatedDashboardMetricsRoute
  '/dashboard/sandbox': typeof AuthenticatedDashboardSandboxRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/dashboard/signals': typeof AuthenticatedDashboardSignalsRoute
  '/dashboard/support': typeof AuthenticatedDashboardSupportRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/ai/council': typeof AuthenticatedAdminAiCouncilRoute
  '/admin/ai/feeds': typeof AuthenticatedAdminAiFeedsRoute
  '/admin/ai/playground': typeof AuthenticatedAdminAiPlaygroundRoute
  '/admin/ai/signals': typeof AuthenticatedAdminAiSignalsRoute
  '/admin/automation/bots': typeof AuthenticatedAdminAutomationBotsRoute
  '/admin/billing/affiliates': typeof AuthenticatedAdminBillingAffiliatesRoute
  '/admin/billing/analytics': typeof AuthenticatedAdminBillingAnalyticsRoute
  '/admin/billing/subscriptions': typeof AuthenticatedAdminBillingSubscriptionsRoute
  '/admin/billing/transactions': typeof AuthenticatedAdminBillingTransactionsRoute
  '/admin/settings/audit': typeof AuthenticatedAdminSettingsAuditRoute
  '/admin/settings/team': typeof AuthenticatedAdminSettingsTeamRoute
  '/admin/support/broadcast': typeof AuthenticatedAdminSupportBroadcastRoute
  '/admin/support/tickets': typeof AuthenticatedAdminSupportTicketsRoute
  '/admin/users/all': typeof AuthenticatedAdminUsersAllRoute
  '/admin/users/compliance': typeof AuthenticatedAdminUsersComplianceRoute
  '/admin/users/risk': typeof AuthenticatedAdminUsersRiskRoute
  '/api/public/nowpayments/webhook': typeof ApiPublicNowpaymentsWebhookRoute
  '/api/public/paystack/webhook': typeof ApiPublicPaystackWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/messages': typeof AuthenticatedMessagesRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/messages': typeof AuthenticatedAdminMessagesRoute
  '/admin/secrets': typeof AuthenticatedAdminSecretsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRouteWithChildren
  '/dashboard/automation': typeof AuthenticatedDashboardAutomationRoute
  '/dashboard/bot': typeof AuthenticatedDashboardBotRoute
  '/dashboard/macro': typeof AuthenticatedDashboardMacroRoute
  '/dashboard/metrics': typeof AuthenticatedDashboardMetricsRoute
  '/dashboard/sandbox': typeof AuthenticatedDashboardSandboxRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/dashboard/signals': typeof AuthenticatedDashboardSignalsRoute
  '/dashboard/support': typeof AuthenticatedDashboardSupportRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/ai/council': typeof AuthenticatedAdminAiCouncilRoute
  '/admin/ai/feeds': typeof AuthenticatedAdminAiFeedsRoute
  '/admin/ai/playground': typeof AuthenticatedAdminAiPlaygroundRoute
  '/admin/ai/signals': typeof AuthenticatedAdminAiSignalsRoute
  '/admin/automation/bots': typeof AuthenticatedAdminAutomationBotsRoute
  '/admin/billing/affiliates': typeof AuthenticatedAdminBillingAffiliatesRoute
  '/admin/billing/analytics': typeof AuthenticatedAdminBillingAnalyticsRoute
  '/admin/billing/subscriptions': typeof AuthenticatedAdminBillingSubscriptionsRoute
  '/admin/billing/transactions': typeof AuthenticatedAdminBillingTransactionsRoute
  '/admin/settings/audit': typeof AuthenticatedAdminSettingsAuditRoute
  '/admin/settings/team': typeof AuthenticatedAdminSettingsTeamRoute
  '/admin/support/broadcast': typeof AuthenticatedAdminSupportBroadcastRoute
  '/admin/support/tickets': typeof AuthenticatedAdminSupportTicketsRoute
  '/admin/users/all': typeof AuthenticatedAdminUsersAllRoute
  '/admin/users/compliance': typeof AuthenticatedAdminUsersComplianceRoute
  '/admin/users/risk': typeof AuthenticatedAdminUsersRiskRoute
  '/api/public/nowpayments/webhook': typeof ApiPublicNowpaymentsWebhookRoute
  '/api/public/paystack/webhook': typeof ApiPublicPaystackWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/_authenticated/billing': typeof AuthenticatedBillingRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/_authenticated/messages': typeof AuthenticatedMessagesRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/_authenticated/admin/messages': typeof AuthenticatedAdminMessagesRoute
  '/_authenticated/admin/secrets': typeof AuthenticatedAdminSecretsRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRouteWithChildren
  '/_authenticated/dashboard/automation': typeof AuthenticatedDashboardAutomationRoute
  '/_authenticated/dashboard/bot': typeof AuthenticatedDashboardBotRoute
  '/_authenticated/dashboard/macro': typeof AuthenticatedDashboardMacroRoute
  '/_authenticated/dashboard/metrics': typeof AuthenticatedDashboardMetricsRoute
  '/_authenticated/dashboard/sandbox': typeof AuthenticatedDashboardSandboxRoute
  '/_authenticated/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/_authenticated/dashboard/signals': typeof AuthenticatedDashboardSignalsRoute
  '/_authenticated/dashboard/support': typeof AuthenticatedDashboardSupportRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/ai/council': typeof AuthenticatedAdminAiCouncilRoute
  '/_authenticated/admin/ai/feeds': typeof AuthenticatedAdminAiFeedsRoute
  '/_authenticated/admin/ai/playground': typeof AuthenticatedAdminAiPlaygroundRoute
  '/_authenticated/admin/ai/signals': typeof AuthenticatedAdminAiSignalsRoute
  '/_authenticated/admin/automation/bots': typeof AuthenticatedAdminAutomationBotsRoute
  '/_authenticated/admin/billing/affiliates': typeof AuthenticatedAdminBillingAffiliatesRoute
  '/_authenticated/admin/billing/analytics': typeof AuthenticatedAdminBillingAnalyticsRoute
  '/_authenticated/admin/billing/subscriptions': typeof AuthenticatedAdminBillingSubscriptionsRoute
  '/_authenticated/admin/billing/transactions': typeof AuthenticatedAdminBillingTransactionsRoute
  '/_authenticated/admin/settings/audit': typeof AuthenticatedAdminSettingsAuditRoute
  '/_authenticated/admin/settings/team': typeof AuthenticatedAdminSettingsTeamRoute
  '/_authenticated/admin/support/broadcast': typeof AuthenticatedAdminSupportBroadcastRoute
  '/_authenticated/admin/support/tickets': typeof AuthenticatedAdminSupportTicketsRoute
  '/_authenticated/admin/users/all': typeof AuthenticatedAdminUsersAllRoute
  '/_authenticated/admin/users/compliance': typeof AuthenticatedAdminUsersComplianceRoute
  '/_authenticated/admin/users/risk': typeof AuthenticatedAdminUsersRiskRoute
  '/api/public/nowpayments/webhook': typeof ApiPublicNowpaymentsWebhookRoute
  '/api/public/paystack/webhook': typeof ApiPublicPaystackWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/support'
    | '/terms'
    | '/billing'
    | '/dashboard'
    | '/messages'
    | '/profile'
    | '/admin/dashboard'
    | '/admin/messages'
    | '/admin/secrets'
    | '/admin/settings'
    | '/dashboard/automation'
    | '/dashboard/bot'
    | '/dashboard/macro'
    | '/dashboard/metrics'
    | '/dashboard/sandbox'
    | '/dashboard/settings'
    | '/dashboard/signals'
    | '/dashboard/support'
    | '/admin/'
    | '/admin/ai/council'
    | '/admin/ai/feeds'
    | '/admin/ai/playground'
    | '/admin/ai/signals'
    | '/admin/automation/bots'
    | '/admin/billing/affiliates'
    | '/admin/billing/analytics'
    | '/admin/billing/subscriptions'
    | '/admin/billing/transactions'
    | '/admin/settings/audit'
    | '/admin/settings/team'
    | '/admin/support/broadcast'
    | '/admin/support/tickets'
    | '/admin/users/all'
    | '/admin/users/compliance'
    | '/admin/users/risk'
    | '/api/public/nowpayments/webhook'
    | '/api/public/paystack/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/support'
    | '/terms'
    | '/billing'
    | '/dashboard'
    | '/messages'
    | '/profile'
    | '/admin/dashboard'
    | '/admin/messages'
    | '/admin/secrets'
    | '/admin/settings'
    | '/dashboard/automation'
    | '/dashboard/bot'
    | '/dashboard/macro'
    | '/dashboard/metrics'
    | '/dashboard/sandbox'
    | '/dashboard/settings'
    | '/dashboard/signals'
    | '/dashboard/support'
    | '/admin'
    | '/admin/ai/council'
    | '/admin/ai/feeds'
    | '/admin/ai/playground'
    | '/admin/ai/signals'
    | '/admin/automation/bots'
    | '/admin/billing/affiliates'
    | '/admin/billing/analytics'
    | '/admin/billing/subscriptions'
    | '/admin/billing/transactions'
    | '/admin/settings/audit'
    | '/admin/settings/team'
    | '/admin/support/broadcast'
    | '/admin/support/tickets'
    | '/admin/users/all'
    | '/admin/users/compliance'
    | '/admin/users/risk'
    | '/api/public/nowpayments/webhook'
    | '/api/public/paystack/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/support'
    | '/terms'
    | '/_authenticated/billing'
    | '/_authenticated/dashboard'
    | '/_authenticated/messages'
    | '/_authenticated/profile'
    | '/_authenticated/admin/dashboard'
    | '/_authenticated/admin/messages'
    | '/_authenticated/admin/secrets'
    | '/_authenticated/admin/settings'
    | '/_authenticated/dashboard/automation'
    | '/_authenticated/dashboard/bot'
    | '/_authenticated/dashboard/macro'
    | '/_authenticated/dashboard/metrics'
    | '/_authenticated/dashboard/sandbox'
    | '/_authenticated/dashboard/settings'
    | '/_authenticated/dashboard/signals'
    | '/_authenticated/dashboard/support'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/ai/council'
    | '/_authenticated/admin/ai/feeds'
    | '/_authenticated/admin/ai/playground'
    | '/_authenticated/admin/ai/signals'
    | '/_authenticated/admin/automation/bots'
    | '/_authenticated/admin/billing/affiliates'
    | '/_authenticated/admin/billing/analytics'
    | '/_authenticated/admin/billing/subscriptions'
    | '/_authenticated/admin/billing/transactions'
    | '/_authenticated/admin/settings/audit'
    | '/_authenticated/admin/settings/team'
    | '/_authenticated/admin/support/broadcast'
    | '/_authenticated/admin/support/tickets'
    | '/_authenticated/admin/users/all'
    | '/_authenticated/admin/users/compliance'
    | '/_authenticated/admin/users/risk'
    | '/api/public/nowpayments/webhook'
    | '/api/public/paystack/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
  ApiPublicNowpaymentsWebhookRoute: typeof ApiPublicNowpaymentsWebhookRoute
  ApiPublicPaystackWebhookRoute: typeof ApiPublicPaystackWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/messages': {
      id: '/_authenticated/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedMessagesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/support': {
      id: '/_authenticated/dashboard/support'
      path: '/support'
      fullPath: '/dashboard/support'
      preLoaderRoute: typeof AuthenticatedDashboardSupportRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/signals': {
      id: '/_authenticated/dashboard/signals'
      path: '/signals'
      fullPath: '/dashboard/signals'
      preLoaderRoute: typeof AuthenticatedDashboardSignalsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/settings': {
      id: '/_authenticated/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof AuthenticatedDashboardSettingsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/sandbox': {
      id: '/_authenticated/dashboard/sandbox'
      path: '/sandbox'
      fullPath: '/dashboard/sandbox'
      preLoaderRoute: typeof AuthenticatedDashboardSandboxRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/metrics': {
      id: '/_authenticated/dashboard/metrics'
      path: '/metrics'
      fullPath: '/dashboard/metrics'
      preLoaderRoute: typeof AuthenticatedDashboardMetricsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/macro': {
      id: '/_authenticated/dashboard/macro'
      path: '/macro'
      fullPath: '/dashboard/macro'
      preLoaderRoute: typeof AuthenticatedDashboardMacroRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/bot': {
      id: '/_authenticated/dashboard/bot'
      path: '/bot'
      fullPath: '/dashboard/bot'
      preLoaderRoute: typeof AuthenticatedDashboardBotRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/automation': {
      id: '/_authenticated/dashboard/automation'
      path: '/automation'
      fullPath: '/dashboard/automation'
      preLoaderRoute: typeof AuthenticatedDashboardAutomationRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/secrets': {
      id: '/_authenticated/admin/secrets'
      path: '/admin/secrets'
      fullPath: '/admin/secrets'
      preLoaderRoute: typeof AuthenticatedAdminSecretsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/messages': {
      id: '/_authenticated/admin/messages'
      path: '/admin/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AuthenticatedAdminMessagesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/dashboard': {
      id: '/_authenticated/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AuthenticatedAdminDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/paystack/webhook': {
      id: '/api/public/paystack/webhook'
      path: '/api/public/paystack/webhook'
      fullPath: '/api/public/paystack/webhook'
      preLoaderRoute: typeof ApiPublicPaystackWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/nowpayments/webhook': {
      id: '/api/public/nowpayments/webhook'
      path: '/api/public/nowpayments/webhook'
      fullPath: '/api/public/nowpayments/webhook'
      preLoaderRoute: typeof ApiPublicNowpaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/users/risk': {
      id: '/_authenticated/admin/users/risk'
      path: '/admin/users/risk'
      fullPath: '/admin/users/risk'
      preLoaderRoute: typeof AuthenticatedAdminUsersRiskRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/users/compliance': {
      id: '/_authenticated/admin/users/compliance'
      path: '/admin/users/compliance'
      fullPath: '/admin/users/compliance'
      preLoaderRoute: typeof AuthenticatedAdminUsersComplianceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/users/all': {
      id: '/_authenticated/admin/users/all'
      path: '/admin/users/all'
      fullPath: '/admin/users/all'
      preLoaderRoute: typeof AuthenticatedAdminUsersAllRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/support/tickets': {
      id: '/_authenticated/admin/support/tickets'
      path: '/admin/support/tickets'
      fullPath: '/admin/support/tickets'
      preLoaderRoute: typeof AuthenticatedAdminSupportTicketsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/support/broadcast': {
      id: '/_authenticated/admin/support/broadcast'
      path: '/admin/support/broadcast'
      fullPath: '/admin/support/broadcast'
      preLoaderRoute: typeof AuthenticatedAdminSupportBroadcastRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/settings/team': {
      id: '/_authenticated/admin/settings/team'
      path: '/team'
      fullPath: '/admin/settings/team'
      preLoaderRoute: typeof AuthenticatedAdminSettingsTeamRouteImport
      parentRoute: typeof AuthenticatedAdminSettingsRoute
    }
    '/_authenticated/admin/settings/audit': {
      id: '/_authenticated/admin/settings/audit'
      path: '/audit'
      fullPath: '/admin/settings/audit'
      preLoaderRoute: typeof AuthenticatedAdminSettingsAuditRouteImport
      parentRoute: typeof AuthenticatedAdminSettingsRoute
    }
    '/_authenticated/admin/billing/transactions': {
      id: '/_authenticated/admin/billing/transactions'
      path: '/admin/billing/transactions'
      fullPath: '/admin/billing/transactions'
      preLoaderRoute: typeof AuthenticatedAdminBillingTransactionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/billing/subscriptions': {
      id: '/_authenticated/admin/billing/subscriptions'
      path: '/admin/billing/subscriptions'
      fullPath: '/admin/billing/subscriptions'
      preLoaderRoute: typeof AuthenticatedAdminBillingSubscriptionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/billing/analytics': {
      id: '/_authenticated/admin/billing/analytics'
      path: '/admin/billing/analytics'
      fullPath: '/admin/billing/analytics'
      preLoaderRoute: typeof AuthenticatedAdminBillingAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/billing/affiliates': {
      id: '/_authenticated/admin/billing/affiliates'
      path: '/admin/billing/affiliates'
      fullPath: '/admin/billing/affiliates'
      preLoaderRoute: typeof AuthenticatedAdminBillingAffiliatesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/automation/bots': {
      id: '/_authenticated/admin/automation/bots'
      path: '/admin/automation/bots'
      fullPath: '/admin/automation/bots'
      preLoaderRoute: typeof AuthenticatedAdminAutomationBotsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/ai/signals': {
      id: '/_authenticated/admin/ai/signals'
      path: '/admin/ai/signals'
      fullPath: '/admin/ai/signals'
      preLoaderRoute: typeof AuthenticatedAdminAiSignalsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/ai/playground': {
      id: '/_authenticated/admin/ai/playground'
      path: '/admin/ai/playground'
      fullPath: '/admin/ai/playground'
      preLoaderRoute: typeof AuthenticatedAdminAiPlaygroundRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/ai/feeds': {
      id: '/_authenticated/admin/ai/feeds'
      path: '/admin/ai/feeds'
      fullPath: '/admin/ai/feeds'
      preLoaderRoute: typeof AuthenticatedAdminAiFeedsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/ai/council': {
      id: '/_authenticated/admin/ai/council'
      path: '/admin/ai/council'
      fullPath: '/admin/ai/council'
      preLoaderRoute: typeof AuthenticatedAdminAiCouncilRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardAutomationRoute: typeof AuthenticatedDashboardAutomationRoute
  AuthenticatedDashboardBotRoute: typeof AuthenticatedDashboardBotRoute
  AuthenticatedDashboardMacroRoute: typeof AuthenticatedDashboardMacroRoute
  AuthenticatedDashboardMetricsRoute: typeof AuthenticatedDashboardMetricsRoute
  AuthenticatedDashboardSandboxRoute: typeof AuthenticatedDashboardSandboxRoute
  AuthenticatedDashboardSettingsRoute: typeof AuthenticatedDashboardSettingsRoute
  AuthenticatedDashboardSignalsRoute: typeof AuthenticatedDashboardSignalsRoute
  AuthenticatedDashboardSupportRoute: typeof AuthenticatedDashboardSupportRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardAutomationRoute:
      AuthenticatedDashboardAutomationRoute,
    AuthenticatedDashboardBotRoute: AuthenticatedDashboardBotRoute,
    AuthenticatedDashboardMacroRoute: AuthenticatedDashboardMacroRoute,
    AuthenticatedDashboardMetricsRoute: AuthenticatedDashboardMetricsRoute,
    AuthenticatedDashboardSandboxRoute: AuthenticatedDashboardSandboxRoute,
    AuthenticatedDashboardSettingsRoute: AuthenticatedDashboardSettingsRoute,
    AuthenticatedDashboardSignalsRoute: AuthenticatedDashboardSignalsRoute,
    AuthenticatedDashboardSupportRoute: AuthenticatedDashboardSupportRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedAdminSettingsRouteChildren {
  AuthenticatedAdminSettingsAuditRoute: typeof AuthenticatedAdminSettingsAuditRoute
  AuthenticatedAdminSettingsTeamRoute: typeof AuthenticatedAdminSettingsTeamRoute
}

const AuthenticatedAdminSettingsRouteChildren: AuthenticatedAdminSettingsRouteChildren =
  {
    AuthenticatedAdminSettingsAuditRoute: AuthenticatedAdminSettingsAuditRoute,
    AuthenticatedAdminSettingsTeamRoute: AuthenticatedAdminSettingsTeamRoute,
  }

const AuthenticatedAdminSettingsRouteWithChildren =
  AuthenticatedAdminSettingsRoute._addFileChildren(
    AuthenticatedAdminSettingsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
  AuthenticatedMessagesRoute: typeof AuthenticatedMessagesRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedAdminDashboardRoute: typeof AuthenticatedAdminDashboardRoute
  AuthenticatedAdminMessagesRoute: typeof AuthenticatedAdminMessagesRoute
  AuthenticatedAdminSecretsRoute: typeof AuthenticatedAdminSecretsRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRouteWithChildren
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminAiCouncilRoute: typeof AuthenticatedAdminAiCouncilRoute
  AuthenticatedAdminAiFeedsRoute: typeof AuthenticatedAdminAiFeedsRoute
  AuthenticatedAdminAiPlaygroundRoute: typeof AuthenticatedAdminAiPlaygroundRoute
  AuthenticatedAdminAiSignalsRoute: typeof AuthenticatedAdminAiSignalsRoute
  AuthenticatedAdminAutomationBotsRoute: typeof AuthenticatedAdminAutomationBotsRoute
  AuthenticatedAdminBillingAffiliatesRoute: typeof AuthenticatedAdminBillingAffiliatesRoute
  AuthenticatedAdminBillingAnalyticsRoute: typeof AuthenticatedAdminBillingAnalyticsRoute
  AuthenticatedAdminBillingSubscriptionsRoute: typeof AuthenticatedAdminBillingSubscriptionsRoute
  AuthenticatedAdminBillingTransactionsRoute: typeof AuthenticatedAdminBillingTransactionsRoute
  AuthenticatedAdminSupportBroadcastRoute: typeof AuthenticatedAdminSupportBroadcastRoute
  AuthenticatedAdminSupportTicketsRoute: typeof AuthenticatedAdminSupportTicketsRoute
  AuthenticatedAdminUsersAllRoute: typeof AuthenticatedAdminUsersAllRoute
  AuthenticatedAdminUsersComplianceRoute: typeof AuthenticatedAdminUsersComplianceRoute
  AuthenticatedAdminUsersRiskRoute: typeof AuthenticatedAdminUsersRiskRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedBillingRoute: AuthenticatedBillingRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
  AuthenticatedMessagesRoute: AuthenticatedMessagesRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedAdminDashboardRoute: AuthenticatedAdminDashboardRoute,
  AuthenticatedAdminMessagesRoute: AuthenticatedAdminMessagesRoute,
  AuthenticatedAdminSecretsRoute: AuthenticatedAdminSecretsRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRouteWithChildren,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminAiCouncilRoute: AuthenticatedAdminAiCouncilRoute,
  AuthenticatedAdminAiFeedsRoute: AuthenticatedAdminAiFeedsRoute,
  AuthenticatedAdminAiPlaygroundRoute: AuthenticatedAdminAiPlaygroundRoute,
  AuthenticatedAdminAiSignalsRoute: AuthenticatedAdminAiSignalsRoute,
  AuthenticatedAdminAutomationBotsRoute: AuthenticatedAdminAutomationBotsRoute,
  AuthenticatedAdminBillingAffiliatesRoute:
    AuthenticatedAdminBillingAffiliatesRoute,
  AuthenticatedAdminBillingAnalyticsRoute:
    AuthenticatedAdminBillingAnalyticsRoute,
  AuthenticatedAdminBillingSubscriptionsRoute:
    AuthenticatedAdminBillingSubscriptionsRoute,
  AuthenticatedAdminBillingTransactionsRoute:
    AuthenticatedAdminBillingTransactionsRoute,
  AuthenticatedAdminSupportBroadcastRoute:
    AuthenticatedAdminSupportBroadcastRoute,
  AuthenticatedAdminSupportTicketsRoute: AuthenticatedAdminSupportTicketsRoute,
  AuthenticatedAdminUsersAllRoute: AuthenticatedAdminUsersAllRoute,
  AuthenticatedAdminUsersComplianceRoute:
    AuthenticatedAdminUsersComplianceRoute,
  AuthenticatedAdminUsersRiskRoute: AuthenticatedAdminUsersRiskRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
  ApiPublicNowpaymentsWebhookRoute: ApiPublicNowpaymentsWebhookRoute,
  ApiPublicPaystackWebhookRoute: ApiPublicPaystackWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
